name: flutter_encriptacion
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  convert: ^3.1.1
  crypto: ^3.0.3
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  pointycastle: ^3.7.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
